const supabaseUrl = 'https://drardmlngfenxvjiehkz.supabase.co';
const supabaseKey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyYXJkbWxuZ2Zlbnh2amllaGt6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY3NzkzNjgzMiwiZXhwIjoxOTkzNTEyODMyfQ.qkLl5feFYQqJvgPGcTgKBLb7SGQQWp_WwCIAGYktNxs';
