name: Flutter Build Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        flutter_channel: [stable, beta]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
      java-version: '11'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: ${{ matrix.flutter_channel }}
        architecture: x64

    - name: Get dependencies
      run: flutter pub get

    - name: Analyze and format code
      run: flutter analyze && dart format . --set-exit-if-changed

    - name: Run tests
      run: flutter test

    - name: Build APK
      if: matrix.os == 'ubuntu-latest' && matrix.flutter_channel == 'stable'
      run: flutter build apk
      run: flutter build appbundle

    - name: Build iOS app
      if: matrix.os == 'macos-latest' && matrix.flutter_channel == 'stable'
      run: flutter build ios --release --no-codesign

    # - name: Archive and export iOS app
    #   if: matrix.os == 'macos-latest'
    #   uses: devbotsxyz/apple-sign@v1
    #   with:
    #     app_path: build/ios/archive/Runner.xcarchive
    #     export_path: build/ios/ipa
    #     export_options_plist_path: Runner/exportOptions.plist
    #     apple_id: ${{ secrets.APPLE_ID }}
    #     apple_id_password: ${{ secrets.APPLE_ID_PASSWORD }}

    - name: Build web app
      if: matrix.os == 'ubuntu-latest' && matrix.flutter_channel == 'stable'
      run: flutter build web

    - name: Build macOS app
      if: matrix.os == 'macos-latest' && matrix.flutter_channel == 'beta'
      run: flutter config --enable-macos-desktop
      run: flutter build macos --release

    - name: Build Windows app
      if: matrix.os == 'windows-latest' && matrix.flutter_channel == 'beta'
      run: flutter config --enable-windows-desktop
      run: flutter build windows --release
      
    - name: Build Linux app
      if: matrix.os == 'ubuntu-latest' && matrix.flutter_channel == 'stable'
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
      run: flutter config --enable-linux-desktop
      run: flutter build linux

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: |
          build/app/outputs/flutter-apk/app-release.apk
          build/web
          build/macos/Build/Products/Release/runner.app
          build/windows/runner/Release/*
          build/linux/x64/*
          # build/ios/ipa/*.ipa
